name: bane
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  lottie: 1.2.1
  google_fonts: 2.2.0
  cloud_firestore: 3.1.6
  google_sign_in: 5.2.3
  get_storage: 2.0.3
  dio: 4.0.4
  line_icons: 2.0.1
  timeago: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/
  uses-material-design: true

