name: amaly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  hexcolor: 2.0.5
  percent_indicator: 3.4.0
  lottie: 1.2.1
  expand_widget: 2.1.0
  custom_radio_grouped_button: 2.1.1
  intl: 0.17.0
  flutter_switch: 0.3.2
  flutter_svg: 0.23.0+1
  google_fonts: 2.1.0
  http: 0.13.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/lottie/
    - asset/icon/
  uses-material-design: true

